/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as IndexRouteImport } from './routes/index'

const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/briefings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/briefings'
  id: '__root__' | '/' | '/briefings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingsRoute: typeof BriefingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingsRoute: BriefingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
